name: Setup OIDC

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  setup-oidc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2
          
      - name: Test AWS access
        run: aws sts get-caller-identity
